// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDApzlumUVJUEkX-3NAlaeTMUCORaW8IP4',
    appId: '1:929366405528:web:3587cd7bc06a2d0f55fbed',
    messagingSenderId: '929366405528',
    projectId: 'class-activity12',
    authDomain: 'class-activity12.firebaseapp.com',
    storageBucket: 'class-activity12.firebasestorage.app',
    measurementId: 'G-77HWSZ7HQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDyTfLf5T8A8hzuLOWyVvPGwIfovqUjnM',
    appId: '1:929366405528:android:d4407d13edd89c0955fbed',
    messagingSenderId: '929366405528',
    projectId: 'class-activity12',
    storageBucket: 'class-activity12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfUwnITmQ_3Dfc-XSCYTfOl4jEo6GFMoQ',
    appId: '1:929366405528:ios:cbcaadfc14c608b255fbed',
    messagingSenderId: '929366405528',
    projectId: 'class-activity12',
    storageBucket: 'class-activity12.firebasestorage.app',
    iosBundleId: 'com.example.classActivity12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfUwnITmQ_3Dfc-XSCYTfOl4jEo6GFMoQ',
    appId: '1:929366405528:ios:cbcaadfc14c608b255fbed',
    messagingSenderId: '929366405528',
    projectId: 'class-activity12',
    storageBucket: 'class-activity12.firebasestorage.app',
    iosBundleId: 'com.example.classActivity12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDApzlumUVJUEkX-3NAlaeTMUCORaW8IP4',
    appId: '1:929366405528:web:06840a4ee93f90a255fbed',
    messagingSenderId: '929366405528',
    projectId: 'class-activity12',
    authDomain: 'class-activity12.firebaseapp.com',
    storageBucket: 'class-activity12.firebasestorage.app',
    measurementId: 'G-LS0R35W9FN',
  );
}
